name: mybookingadv
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  calendar_date_picker2: ^0.5.3
  flutter_svg_provider: ^1.0.7
  dotted_border: ^2.1.0
  intl: ^0.18.0
  connectivity_plus: ^5.0.2
  syncfusion_flutter_datepicker: ^25.2.5
  # syncfusion_flutter_datepicker: ^25.2.5
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  # fonts: 
    # - family: Inika
    #   fonts: 
    #     - asset: assets/fonts/Inika.ttf
    #       weight: 400
    # - family: Inter
    #   fonts: 
    #     - asset: assets/fonts/InterMedium.ttf
    #       weight: 500
    #     - asset: assets/fonts/InterBold.ttf
    #       weight: 700
    #     - asset: assets/fonts/InterLight.ttf
    #       weight: 300
    #     - asset: assets/fonts/InterRegular.ttf
    #       weight: 400
    #     - asset: assets/fonts/InterSemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/InterThin.ttf
    #       weight: 100
    # - family: Roboto
    #   fonts: 
    #     - asset: assets/fonts/RobotoBold.ttf
    #       weight: 700
    #     - asset: assets/fonts/RobotoRegular.ttf
    #       weight: 400
    #     - asset: assets/fonts/RobotoBlack.ttf
    #       weight: 900
    #     - asset: assets/fonts/RobotoMedium.ttf
    #       weight: 500
